version: '3.8'

services:
  web:
    build: ./frontend
    container_name: demo_web
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - default
      - npm_network # <- Conexión vital para Nginx Proxy Manager

  backend:
    build: ./backend
    container_name: demo_backend
    restart: unless-stopped
    networks:
      - default # Solo visible internamente

  # Agregamos Redis de ejemplo (opcional, sin puertos expuestos)
  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - default

networks:
  # Declaramos la red externa donde vive NPM
  npm_network:
    name: npm_network # Asegúrate de que coincida con el nombre real en tu servidor
    external: true